DELETE http://localhost:3000/user/673f57458dddea90a5246214
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3M2Y1ZDFiNDJjNzU4MWU2YmIxYTA3ZiIsImlhdCI6MTczMjIwNzYyMywiZXhwIjoxNzMyMjExMjIzfQ.1FcGUk6whJ2Fye9NNmOTjqYn45X7qfU2ZEkIm2LL8E0
